FROM openjdk:8-jdk-slim

MAINTAINER mariem.zouari@enis.tn

ARG JMETER_VERSION="5.4.3"

ENV JMETER_VERSION ${JMETER_VERSION}
ENV JMETER_HOME /jmeter/apache-jmeter-$JMETER_VERSION
ENV PATH $JMETER_HOME/bin:$PATH

# INSTALL PRE-REQ		
RUN apt-get clean \
    && apt-get update \
    && apt-get -qy install \
    wget \
    telnet \
    iputils-ping \
    unzip

# INSTALL JMETER BASE 
RUN mkdir /jmeter
WORKDIR /jmeter
 
RUN wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
    && tar -xzf apache-jmeter-$JMETER_VERSION.tgz \
    && rm apache-jmeter-$JMETER_VERSION.tgz \
    && mkdir /jmeter-plugins \
    && cd /jmeter-plugins/ \
    && wget https://jmeter-plugins.org/downloads/file/JMeterPlugins-ExtrasLibs-1.4.0.zip \
    && unzip -o JMeterPlugins-ExtrasLibs-1.4.0.zip -d /jmeter/apache-jmeter-$JMETER_VERSION

WORKDIR $JMETER_HOME 

COPY user.properties bin/user.properties    
COPY install_plugin-manager.sh .

RUN chmod +x install_plugin-manager.sh 
RUN ./install_plugin-manager.sh
WORKDIR /jmeter/apache-jmeter-5.4.3		
RUN PluginsManagerCMD.sh install jpgc-webdriver=3.3