FROM openjdk:8-jdk-slim

MAINTAINER mariem.zouari@enis.tn

ARG JMETER_VERSION="5.4.3"

ENV JMETER_VERSION ${JMETER_VERSION}
ENV JMETER_HOME /jmeter/apache-jmeter-$JMETER_VERSION


# INSTALL PRE-REQ		
RUN apt-get clean \
    && apt-get update \
    && apt-get -qy install \
    wget \
    telnet \
    iputils-ping \
    unzip

# INSTALL JMETER BASE 
RUN mkdir /jmeter
WORKDIR /jmeter
 
RUN wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
    && tar -xzf apache-jmeter-$JMETER_VERSION.tgz \
    && rm apache-jmeter-$JMETER_VERSION.tgz \
    && mkdir /jmeter-plugins \
    && cd /jmeter-plugins/ \
    && wget https://jmeter-plugins.org/downloads/file/JMeterPlugins-ExtrasLibs-1.4.0.zip \
    && unzip -o JMeterPlugins-ExtrasLibs-1.4.0.zip -d /jmeter/apache-jmeter-$JMETER_VERSION

WORKDIR $JMETER_HOME 

COPY user.properties bin/user.properties    
#COPY install_plugin-manager.sh .

ARG JMETER_PMANAGER_VERSION="1.7"
ARG CMDRUNNER_VERSION="2.2"
ARG JMETER_PLUGINS_PATH="/jmeter/apache-jmeter-$JMETER_VERSION/lib/ext"

# Install plugins
RUN wget http://central.maven.org/maven2/kg/apc/jmeter-plugins-manager/${JMETER_PMANAGER_VERSION}/jmeter-plugins-manager-${JMETER_PMANAGER_VERSION}.jar \
  && mv ./jmeter-plugins-manager-${JMETER_PMANAGER_VERSION}.jar ${JMETER_HOME}/lib/ext \
  && wget http://repo1.maven.org/maven2/kg/apc/cmdrunner/${CMDRUNNER_VERSION}/cmdrunner-${CMDRUNNER_VERSION}.jar \
  && mv ./cmdrunner-${CMDRUNNER_VERSION}.jar ${JMETER_HOME}/lib \
  && java -cp ${JMETER_HOME}/lib/ext/jmeter-plugins-manager-${JMETER_PMANAGER_VERSION}.jar org.jmeterplugins.repository.PluginManagerCMDInstaller \
  && ${JMETER_HOME}/bin/PluginsManagerCMD.sh install-all-except 

#RUN chmod +x install_plugin-manager.sh 
#RUN ./install_plugin-manager.sh
		
ENV PATH $JMETER_HOME/bin:$PATH